### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by matthewp** [elm-lang/debug.elm-lang.org#3]
I followed the installation instructions exactly, on two separate computers, and when it comes to running `./dist/build/elm-debugger/elm-debugger`, I get this error message:

```
Initializing Server
elm-debugger: build: getDirectoryContents: does not exist (No such file or directory)
```

I'm not sure what directory it is referring to.

**Comment by jvoigtlaender** [comment]
Close this issue now? Nobody will have to build from this repo anymore, as the revised README states.

**Comment by matthewp** [comment]
Cool, thanks.
