### ISSUE TITLE
Add Deprecated Message to README.md

### ISSUE THREAD

**Issue by ryanmtaylor** [elm-lang/debug.elm-lang.org#6]
I'd submit a pull request, but I'd have to send an agreement and honestly I don't think it'd be that helpful.

It would be nice if this repo mentioned, in the README.md, that it was deprecated/moved to [elm-reactor](https://github.com/elm-lang/elm-reactor).  Or even just recommended `npm install -g elm`.  http://debug.elm-lang.org/ still links to this repo in the first paragraph (at least).

For the record: As far as installing, you'll need to run `cabal sandbox init` and then `cabal install 'Elm >= 0.13'` (so it resolves the older dependencies correctly).  Lastly, it'd need to use an older version of `base` which can't be installed by cabal anyway.  The directions here reference the old `Elm` repository, and refers to itself as `elm-debugger` instead of `debug.elm-lang.org`.

**Comment by jvoigtlaender** [comment]
Close this issue now? The README was revised and is now pointing to `elm-reactor`.
